controller:
  image:
    registry: registry.k8s.io
    image: ingress-nginx/controller
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    behavior:
      scaleDown:
        stabilizationWindowSeconds: 300
        policies:
        - type: Pods
          value: 1
          periodSeconds: 180
      scaleUp:
        stabilizationWindowSeconds: 300
        policies:
        - type: Pods
          value: 2
          periodSeconds: 60

  watchIngressWithoutClass: true

  service:
    enabled: true
    annotations:
        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
        service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
        service.beta.kubernetes.io/aws-load-balancer-type: nlb
        service.beta.kubernetes.io/aws-load-balancer-internal: true

  metrics:
    enabled: true
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"

  resources:
      requests:
        cpu: 500m
        memory: 400Mi
      limits:
        cpu: 1
        memory: 1Gi

serviceAccount:
  create: true